// GENERATED by tools/generate_ui_strings.dart — do not edit.
//
// Machine translations of UI chrome, produced offline by
// TranslatePsy-AfriSLM. Consulted *after* the hand-curated
// kUiStrings and kUiStringsMore, so a reviewed entry always
// wins over anything here. Regenerate rather than hand-edit.
//
// Empty until the generator has been run — `tr()` falls through to English
// for every key, which is exactly the behaviour before this table existed.
const kUiStringsGenerated = <String, Map<String, String>>{};
